// lib/widget/outerWildsAlbum.ts
export const outerWildsAlbum = [
	{ artist: "Andrew Prahlow", title: "Timber Hearth" },
	{ artist: "Andrew Prahlow", title: "Outer Wilds" },
	{ artist: "Andrew Prahlow", title: "The Museum" },
	{ artist: "Andrew Prahlow", title: "Space" },
	{ artist: "Andrew Prahlow", title: "Castaways" },
	{ artist: "Andrew Prahlow", title: "The Sun Station" },
	{ artist: "Andrew Prahlow", title: "Main Title" },
	{ artist: "Andrew Prahlow", title: "The Search" },
	{ artist: "Andrew Prahlow", title: "The Uncertainty Principle" },
	{ artist: "Andrew Prahlow", title: "End Times" },
	{ artist: "Andrew Prahlow", title: "22 Minutes" },
	{ artist: "Andrew Prahlow", title: "The Nomai" },
	{ artist: "Andrew Prahlow", title: "The Ash Twin Project" },
	{ artist: "Andrew Prahlow", title: "Dark Bramble" },
	{ artist: "Andrew Prahlow", title: "Giant's Deep" },
	{ artist: "Andrew Prahlow", title: "Nomai Ruins" },
	{ artist: "Andrew Prahlow", title: "Final Voyage" },
	{ artist: "Andrew Prahlow", title: "The Ancient Glade" },
	{ artist: "Andrew Prahlow", title: "Curiosity" },
	{ artist: "Andrew Prahlow", title: "Travelers" },
	{ artist: "Andrew Prahlow", title: "Let There Be Light" },
	{ artist: "Andrew Prahlow", title: "14.3 Billion Years" },
	{ artist: "Andrew Prahlow", title: "Morning" },
	{ artist: "Andrew Prahlow", title: "Campfire Song" },
	{ artist: "Andrew Prahlow", title: "Into the Wilds" },
	{ artist: "Andrew Prahlow", title: "Arrow of Time" },
	{ artist: "Andrew Prahlow", title: "We Have Liftoff" },
	{ artist: "Andrew Prahlow", title: "A Terrible Fate" }
];
