import { Project } from "./model";

export const projects: Project[] = [
	{
		id: "collatz-viz",
		rank: 9,
		slug: "collatz-viz",
		title: "Collatz Conjecture Explorer",
		tagline: "Nobody has proved it. here's what it looks like",
		description: "Interactive visualization of stopping-time landscapes for the Collatz Conjecture, with original research angles on sequence behavior.",
		tags: ["software engineering"],
		tech: ["Rust", "WebAssembly", "TypeScript", "Vite", "Canvas API", "Web Workers"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/collatz-explorer",
		image: "/images/projects/collatz.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "groat",
		rank: 1,
		slug: "groat",
		title: "groat",
		tagline: "Every token counts.",
		description:
			"A self-hosted LLM proxy that reduces API costs through semantic response caching and intelligent model routing, providing a drop-in OpenAI-compatible endpoint that requires no changes to existing applications.",
		tags: ["systems programming", "machine learning"],
		tech: ["Rust", "Tokio", "OpenAI-compatible APIs", "Vector databases", "Embeddings", "LLMs"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/groat",
		live: "https://getgroat.vercel.app/",
		image: "/images/projects/groat.png",
		featured: true,
		hasCaseStudy: false
	},
	{
		id: "mapreduce-engine",
		rank: 10,
		slug: "mapreduce-engine",
		title: "creduce",
		tagline: "Hadoop is overkill. built it anyway, from scratch.",
		description:
			"A MapReduce engine built from scratch in C - no Hadoop, no JVM. Full map-shuffle-reduce pipeline with a pthreads worker pool, verified on 217k key-value pairs.",
		tags: ["systems programming", "data engineering"],
		tech: ["C", "pthreads", "Make", "GCC"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/creduce",
		image: "/images/projects/creduce.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "calvin-hobbes-api",
		rank: 8,
		slug: "calvin-hobbes-api",
		title: "Calvin & Hobbes Quote API",
		tagline: "Philosophy from a six-year-old, on demand",
		description:
			"A lightweight Flask service that exposes a collection of Calvin and Hobbes quotes through a simple JSON API. Built for developers looking to integrate a little humor, nostalgia, and personality into their applications. Implemented in your application with a single HTTP request, no authentication required.",
		tags: ["software engineering"],
		tech: ["Python", "Flask", "Vercel", "Git", "Rest API"],
		status: "completed",
		year: 2024,
		github: "https://github.com/bhavv04/calandhobbes-quoter",
		live: "https://calandhobbes-quoter-7gd9mxl0e-bhavdeeps-projects.vercel.app/api/quotes/random",
		image: "/images/projects/calandhobbes.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "thunderhead",
		rank: 2,
		slug: "thunderhead",
		title: "Thunderhead",
		tagline: "Silent observation. no captchas. no cloudflare.",
		description:
			"A lightweight reverse proxy that passively scores the intent of every incoming HTTP request using behavioral signals, rate, crawl patterns, and header anomalies, to silently tarpit or block bot traffic.",
		tags: ["systems programming", "software engineering"],
		tech: ["Go", "net/http", "httputil.ReverseProxy", "Bubbletea", "Lipgloss", "Next.js", "Docker", "ngrok"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/thunderhead",
		live: "https://getthunderhead.vercel.app/",
		image: "/images/projects/thunderhead.png",
		featured: true,
		hasCaseStudy: true
	},
	{
		id: "verrere",
		rank: 4,
		slug: "verrere",
		title: "verrere",
		tagline: "Tinder for books. Swipe right to build your shelf",
		description:
			"A full-stack book discovery platform built around a swipe-based interface. Browse personalized recommendations, build your reading list, and let the app learn your genre preferences while ensuring every recommendation is unique.",
		tags: ["software engineering", "data engineering"],
		tech: ["Next.js 15", "TypeScript", "Tailwind CSS", "Framer Motion", "Clerk", "Neon", "Prisma", "PostgreSQL"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/verrere",
		live: "https://verrere.vercel.app/",
		image: "/images/projects/verrere.png",
		featured: true,
		hasCaseStudy: true
	},
	{
		id: "funes",
		rank: 3,
		slug: "funes",
		title: "funes",
		tagline: "Your machine's memory, queryable.",
		description:
			"A privacy-first, local-only daemon CLI tool that that builds a semantic index of your development history and indexes your files, notes, and terminal history into a vector database, allowing you to query your past work using natural language.",
		tags: ["systems programming", "machine learning", "data engineering", "software engineering"],
		tech: ["Rust", "Ollama", "SQLite", "cargo", "Tokio", "Clap", "Vector databases", "LLMs"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/funes",
		image: "/images/projects/funes.png",
		live: "https://get-funes.vercel.app/",
		featured: true,
		hasCaseStudy: true
	},
	{
		id: "ember",
		rank: 6,
		slug: "ember",
		title: "Ember",
		tagline: "Not a calorie tracker. a deficit visualizer.",
		description:
			"A weight-loss planning tool that visualizes the math behind calorie deficits instead of simply logging meals. It adapts to your changing weight, estimates your daily energy expenditure, projects your goal date, and shows exactly how much activity or calorie reduction is needed to reach your target.",
		tags: ["software engineering"],
		tech: ["Next.js 15", "TypeScript", "Tailwind CSS", "shadcn/ui", "Clerk", "Neon", "Prisma", "PostgreSQL"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/ember",
		image: "/images/projects/ember.png",
		live: "https://myember.vercel.app/",
		featured: true,
		hasCaseStudy: false
	},
	{
		id: "terraseed",
		rank: 7,
		slug: "terraseed",
		title: "Terraseed",
		tagline: "30 years of climate data, one planting score",
		description:
			"Predicts optimal planting windows for any location on Earth using 30 years of ERA5 climate reanalysis data. A composite scoring model weighs historical temperature stability, precipitation, and frost risk to surface the best planting dates for a given crop and location.",
		tags: ["machine learning", "data engineering", "data visualization"],
		tech: ["Python", "Plotly Dash", "scikit-learn", "xarray"],
		status: "active",
		year: 2025,
		github: "https://github.com/bhavv04/terraseed",
		live: "https://bhavv04.github.io/terraseed/",
		image: "/images/projects/terraseed.png",
		featured: true,
		hasCaseStudy: false
	},
	{
		id: "redis-c",
		rank: 11,
		slug: "redis-c",
		title: "Custom Redis",
		tagline: "Redis, from scratch, in C.",
		description: "A ground-up implementation of a Redis-compatible in-memory key-value store written in C.",
		tags: ["systems programming"],
		tech: ["C", "POSIX sockets", "RESP protocol", "Make"],
		status: "completed",
		year: 2026,
		github: "https://github.com/bhavv04/redis",
		live: "",
		image: "/images/projects/redis.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "gaia",
		rank: 7,
		slug: "gaia",
		title: "Gaia",
		tagline: "Cross-domain cascade failure prediction in ecological systems",
		description:
			"Models multi-layered environmental dependencies-dead zones, food webs, and atmospheric drift-to predict how local structural collapses cascade across global ecological boundaries.",
		tags: ["machine learning", "data engineering"],
		tech: ["Python", "NetworkX", "PyTorch Geometric", "xarray", "GeoPandas"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/gaia",
		image: "/images/projects/gaia.png",
		featured: true,
		hasCaseStudy: false
	},
	{
		id: "awkrs",
		rank: 12,
		slug: "awkrs",
		title: "GNU AWK in rust",
		tagline: "awk, rewritten in Rust, without the archaeology",
		description:
			"A Rust implementation of the AWK text-processing language, rebuilding the core pattern-action model from scratch with modern memory safety guarantees.",
		tags: ["systems programming"],
		tech: ["Rust"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/awkrs",
		live: "",
		image: "/images/projects/awkrs.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "solace",
		rank: 5,
		slug: "solace",
		title: "solace",
		tagline: "Predicting wildfire spread, not just visualizing it.",
		description:
			"A wildfire spread simulator implementing the Canadian Forest Fire Behaviour Prediction (FBP) System to model boreal forest fire growth from real weather, terrain, and fuel data, validated against the 2016 Fort McMurray wildfire.",
		tags: ["systems programming", "data visualization", "data engineering", "computer vision"],
		tech: ["Rust", "Python", "GeoPandas", "Rasterio", "xarray", "ERA5", "Canadian FBP System", "Fire Weather Index (FWI)", "GIS"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/solace",
		live: "",
		image: "/images/projects/solace.png",
		featured: true,
		hasCaseStudy: false
	}
];
